name: Windows 2022

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Configure ngrok auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Create wallpaper
      run: |
        # (Optional) Create a dummy wallpaper if you still need it
        Add-Content wallpaper.bat '@echo off'
        Add-Content wallpaper.bat 'echo Wallpaper script here'
        Copy-Item wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat

    - name: Start ngrok tunnel
      run: Start-Process powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Create start.bat
      run: |
        Add-Content start.bat '@echo off'
        Add-Content start.bat 'echo RDP Tunnel started'
        Add-Content start.bat 'pause'
        cmd /c start.bat

    - name: Keep session alive
      run: |
        Add-Content loop.bat '@echo off'
        Add-Content loop.bat ':loop'
        Add-Content loop.bat 'timeout /t 3600'
        Add-Content loop.bat 'goto loop'
        cmd /c loop.bat
